### ISSUE TITLE
Question: PyData Sphinx Theme with ABlog

### ISSUE THREAD

**Issue by PhilipMay** [choldgraf/choldgraf.github.io#12]
Hi,
I have seen your blog about using Sphinx and ABlog.
You use PyData Sphinx Theme with ABlog.
A while ago I was also experimenting with ABlog but was not able to change the theme.
That's why I was using Dokuwiki.

**My Question:** Does it need any tweaking to use PyData Sphinx Theme with ABlog
or is it just an drop in?

Thanks and have a nice Weekend
Philip

**Comment by choldgraf** [comment]
hmmm in my case there didn't need to be much extra tweaking - I just configured them separately. I do think there was some weirdness with the sidebar and lots of tag clouds and such, but nothing major

**Comment by PhilipMay** [comment]
Ok. Thanks.
