### ISSUE TITLE
link to your post on RUST governance broken

### ISSUE THREAD

**Issue by sappelhoff** [choldgraf/choldgraf.github.io#13]
Hi @choldgraf, your link "https://predictablynoisy.com/rust-governance" seems broken, you used to use it here:

https://github.com/choldgraf/choldgraf.github.io/blame/64d0097408b7d9d3a86088947310dcc10c400b17/posts/2019/2019-10-13-rust-jupyter-governance.md#L10

this is related to https://github.com/bids-standard/bids-website/pull/189 - we were referring to that post of yours from our docs.

What's the status with that page? is it broken, or did you want to remove/rename/... it? 

Thanks :)

**Comment by choldgraf** [comment]
ah good catch! try again :-) https://predictablynoisy.com/rust-governance/

**Comment by sappelhoff** [comment]
excellent, thanks!
